services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    build: requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    networks:
      - net

  wordpress:
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    build: requirements/wordpress
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    networks:
      - net

  mariadb:
    container_name: mariadb
    restart: unless-stopped
    build: requirements/mariadb
    healthcheck:
      test: "/usr/bin/mysql --user=wpuser --password=password --execute \"SHOW DATABASES;\""
      retries: 10
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - net

networks:
  net:
    driver: bridge
volumes:
  db_data:
    driver: local
    driver_opts:
      device: /home/jcros/data/mariadb
      o: bind
      type: none
  wp_data:
    driver: local
    driver_opts:
      device: /home/jcros/data/wordpress
      o: bind
      type: none
