services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    build: requirements/nginx
    ports:
      - "443:443"
      # - "80:80"
    volumes:
      # - ./web:/var/www/html
      - wp_data:/var/www/html
    networks:
      - net

  wordpress:
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      - mariadb
    build: requirements/wordpress
    volumes:
      - wp_data:/var/www/html
      # - ./web:/var/www/html
    env_file:
      - .env
    networks:
      - net

  mariadb:
    container_name: mariadb
    restart: unless-stopped
    build: requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - net

networks:
  net:
    driver: bridge
volumes:
  db_data:
  wp_data:
# volumes:
#   wp_data:
#     name: wordpress
#     driver: local
#     driver_opts:
#       device: ./requirements/wordpress/
#       o: bind
#       type: none
#   db_data:
#     name: mariadb
#     driver: local
#     driver_opts:
#       device: ./requirements/mariadb/
#       o: bind
#       type: none
# version: "3.9"

# services:
#   mariadb:
#     container_name: mariadb
#     restart: always
#     build: ./requirements/mariadb
#     volumes:
#       - db_data:/var/lib/mysql
#     env_file:
#       - .env
#     networks:
#       - net

#   nginx:
#     container_name: nginx
#     restart: always
#     build: ./requirements/nginx
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - wp_data:/var/www/html
#     networks:
#       - net

#   wordpress:
#     container_name: wordpress
#     restart: always
#     depends_on:
#       - mariadb
#     build: ./requirements/wordpress
#     volumes:
#       - wp_data:/var/www/html
#     env_file:
#       - .env
#     networks:
#       - net

# networks:
#   net:
#     driver: bridge

# volumes:
#   db_data:
#   wp_data:
#     image: mariadb:latest
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: MyR00tMySQLPa$$5w0rD
#       MYSQL_DATABASE: MyWordPressDatabaseName
#       MYSQL_USER: MyWordPressUser
#       MYSQL_PASSWORD: Pa$$5w0rD
#   wordpress:
#     image: wordpress:latest
#     container_name: wordpress-blog
#     depends_on:
#       - db
#     ports:
#       - "8000:80"
#       - "443:443"
#     restart: always
#     environment:
#       WORDPRESS_DB_HOST: mysql
#       WORDPRESS_DB_USER: admin
#       WORDPRESS_DB_PASSWORD: password
#       WORDPRESS_DB_NAME: wordpress

#     volumes: ["./:/var/www/html"]
